CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT PRIMARY KEY,
    NM_FUNCIONARIO VARCHAR(100) NOT NULL,
    DT_ADMISSAO DATE NOT NULL,
    SALARIO_BASE DECIMAL(10, 2) NOT NULL,
    ID_DEPARTAMENTO INT,
    ID_CARGO INT,
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO)
);

CREATE INDEX idx_nm_funcionario ON FUNCIONARIO(NM_FUNCIONARIO);
